// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CO_VM.Models;

public partial class Booking
{
    public int BookId { get; set; }

    public int UserId { get; set; }

    public int? FamilyId { get; set; }

    public int SlotId { get; set; }

    public int VaccineId { get; set; }

    public DateTime BookingDate { get; set; }

    public string Status { get; set; }

    public int? DoseNumber { get; set; }

    public DateOnly? VaccinatedOn { get; set; }

    public string PaymentMode { get; set; }

    public virtual Family Family { get; set; }

    public virtual Slot Slot { get; set; }

    public virtual User User { get; set; }

    public virtual Vaccine Vaccine { get; set; }

    public virtual ICollection<VaccineCertificate> VaccineCertificates { get; set; } = new List<VaccineCertificate>();
}