// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CO_VM.Models;

public partial class Family
{
    public int FamilyId { get; set; }

    public int UserId { get; set; }


    [Required(ErrorMessage = "UserName is required")]
    [StringLength(50, ErrorMessage = "Username cannot exceed 50 characters")]
    public string FullName { get; set; }

    [Required(ErrorMessage = "Date of Birth is required")]
    public DateOnly Dob { get; set; }

    [Required(ErrorMessage = "Gender is required")]
    [RegularExpression(@"^(Male|Female|Other)$", ErrorMessage = "Gender must be Male, Female, or Other")]
    public string Gender { get; set; }

    [Required(ErrorMessage = "Aadhar no is required")]
    [RegularExpression(@"^\d{12}$", ErrorMessage = "Aadhaar number must be 12 digits")]
    public string AadhaarNo { get; set; }

    public int? RelationId { get; set; }

    public virtual Relation Relation { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Slot> Slots { get; set; } = new List<Slot>();

    public virtual User User { get; set; }
}