// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CO_VM.Models;

public partial class Relation
{
    public int RelationId { get; set; }

    public string RelationType { get; set; }

    public virtual ICollection<Family> Families { get; set; } = new List<Family>();
}