// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CO_VM.Models;

public partial class VaccineCertificate
{
    public int CertificateId { get; set; }

    public int BookId { get; set; }

    public byte[] Certificate { get; set; }

    public DateOnly CertificateDate { get; set; }

    public virtual Booking Book { get; set; }
}