// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CO_VM.Models;

public partial class Vaccine
{
    public int VaccineId { get; set; }

    public string VaccineName { get; set; }

    public string Manufacturer { get; set; }

    public int? DosesRequired { get; set; }

    public int? Stock { get; set; }

    public byte[] Image { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Slot> Slots { get; set; } = new List<Slot>();

    public virtual ICollection<VaccinationFeedback> VaccinationFeedbacks { get; set; } = new List<VaccinationFeedback>();

    public virtual ICollection<VaccineCentre> VaccineCentres { get; set; } = new List<VaccineCentre>();
}