// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CO_VM.Models;

public partial class VaccinationFeedback
{
    public int FeedbackId { get; set; }

    public int UserId { get; set; }

    public int VaccineId { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public byte? Rating { get; set; }

    public string Feedback { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public virtual User User { get; set; }

    public virtual Vaccine Vaccine { get; set; }
}